name: DaraeVoice
options:
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: ko
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.soonhak.DaraeVoice
    SWIFT_VERSION: 5.0
packages: {}
targets:
  DaraeVoice:
    type: application
    platform: iOS
    sources:
      - path: DaraeVoice
    resources:
      - path: Assets
    settings:
      base:
        INFOPLIST_FILE: DaraeVoice/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: DaraeVoice/Info.plist
      properties:
        UILaunchScreen: {}
        NSMicrophoneUsageDescription: "음성 입력을 위해 마이크가 필요합니다."
        NSSpeechRecognitionUsageDescription: "음성 인식을 위해 음성 인식 권한이 필요합니다."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
